export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const PRODUCT_DETAIL_REQ = "PRODUCT_DETAIL_REQ"
export const PRODUCT_DETAIL_REQ_SUCCESS = "PRODUCT_DETAIL_REQ_SUCCESS"
export const PRODUCT_DETAIL_REQ_FAIL = "PRODUCT_DETAIL_REQ_FAIL"
